/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export type CommentListParams = {
  /**
 * 부모 댓글 여부.  
이 필터가 True 이면 부모 댓글만 조회합니다.  
부모 댓글이란 parent_id 가 NULL 인 댓글을 의미합니다.
 */
  is_parent?: boolean;
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * 부모 댓글 ID.
   */
  parent_id?: number;
  user?: number;
  video_data?: number;
};
