/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `LONGTUBE` - 롱튜브
 * `SHORTS` - 유튜브 쇼츠
 * `REELS` - 인스타릴스
 * `TIKTOK` - 틱톡컨텐츠
 */
export type ContentTypeEnum =
  (typeof ContentTypeEnum)[keyof typeof ContentTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentTypeEnum = {
  LONGTUBE: "LONGTUBE",
  SHORTS: "SHORTS",
  REELS: "REELS",
  TIKTOK: "TIKTOK",
} as const;
