/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface History {
  readonly rstype: string;
  readonly rsdate: string;
  /** 소수점의 포인트를 문자열로 표시합니다. */
  readonly points: string;
}
