/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface InputPoint {
  /**
   * 입금할 포인트를 소수점 단위의 string 타입으로 입력합니다.  
1 이상의 값으로 입력해야 합니다.  
총 16자리 중 정수 부분 10자리, 소수 부분 6자리까지 입력 가능합니다.
   * @maxLength 17
   */
  point: string;
  /** 동영상 제목 등 기타 내용을 입력합니다. */
  note: string;
  /**
   * 포인트 구분을 입력합니다.  
0: 동영상 시청 P, 1: 좋아요/싫어요 P, 2: 스크롤 P
   * @maxLength 1
   */
  flag: string;
}
