/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export type LikeHistoryListLikeType =
  (typeof LikeHistoryListLikeType)[keyof typeof LikeHistoryListLikeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LikeHistoryListLikeType = {
  dislike: "dislike",
  like: "like",
} as const;
