/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { LikeHistoryListLikeType } from "./likeHistoryListLikeType";

export type LikeHistoryListParams = {
  /**
   * * `like` - 좋아요
   * `dislike` - 싫어요
   */
  like_type?: LikeHistoryListLikeType;
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  user?: number;
};
