/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `like` - 좋아요
 * `dislike` - 싫어요
 */
export type LikeTypeEnum = (typeof LikeTypeEnum)[keyof typeof LikeTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LikeTypeEnum = {
  like: "like",
  dislike: "dislike",
} as const;
