/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUserListPaging } from "./paginatedUserListPaging";
import type { User } from "./user";

export interface PaginatedUserList {
  paging: PaginatedUserListPaging;
  items: User[];
}
