/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUserWatchHistoryListPaging } from "./paginatedUserWatchHistoryListPaging";
import type { UserWatchHistory } from "./userWatchHistory";

export interface PaginatedUserWatchHistoryList {
  paging: PaginatedUserWatchHistoryListPaging;
  items: UserWatchHistory[];
}
