/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedVideoDataListPagingNext } from "./paginatedVideoDataListPagingNext";

export type PaginatedVideoDataListPaging = {
  page: number;
  total: number;
  size: number;
  next?: PaginatedVideoDataListPagingNext;
};
