/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedVideoDataListPaging } from "./paginatedVideoDataListPaging";
import type { VideoData } from "./videoData";

export interface PaginatedVideoDataList {
  paging: PaginatedVideoDataListPaging;
  items: VideoData[];
}
