/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUserSearchHistoryListPaging } from "./paginatedUserSearchHistoryListPaging";
import type { UserSearchHistory } from "./userSearchHistory";

export interface PaginatedUserSearchHistoryList {
  paging: PaginatedUserSearchHistoryListPaging;
  items: UserSearchHistory[];
}
