/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLikeHistoryListPaging } from "./paginatedLikeHistoryListPaging";
import type { LikeHistory } from "./likeHistory";

export interface PaginatedLikeHistoryList {
  paging: PaginatedLikeHistoryListPaging;
  items: LikeHistory[];
}
