/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { UserForComment } from "./userForComment";

export interface Parent {
  readonly id: number;
  readonly user: UserForComment;
  /**
   * 최대 500자까지 허용합니다.
   * @maxLength 500
   */
  content: string;
  readonly create_time: string;
}
