/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { UserForComment } from "./userForComment";
import type { VideoData } from "./videoData";
import type { Parent } from "./parent";

export interface PatchedUserComments {
  readonly id?: number;
  readonly user?: UserForComment;
  video_data_id?: number;
  readonly video_data?: VideoData;
  /**
   * 최대 500자까지 허용합니다.
   * @maxLength 500
   */
  content?: string;
  readonly parent?: Parent;
  /**
   * 대댓글인 경우, 부모 댓글의 ID를 입력합니다.
   * @nullable
   */
  parent_id?: number | null;
  /** 이 댓글에 달린 대댓글 수입니다. 0이라면 대댓글이 없습니다. */
  readonly replies_count?: number;
  readonly create_time?: string;
}
