/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentTypeEnum } from "./contentTypeEnum";

export interface PatchedVideoData {
  readonly id?: number;
  readonly create_time?: string;
  readonly update_time?: string;
  /** @maxLength 120 */
  title?: string;
  /** @nullable */
  description?: string | null;
  /**
   * 유튜브, 인스타그램, 틱톡 등의 그 서비스 고유 구분자 id
   * @maxLength 120
   */
  external_video_id?: string;
  content_type?: ContentTypeEnum;
  /** @nullable */
  tag?: string | null;
  /** @nullable */
  category?: string | null;
  /**
   * JSON.stringify
   * @nullable
   */
  api_response?: string | null;
}
