/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export type PointRetrieveParams = {
  /**
 * 조회하고자 하는 포인트를 적습니다.  
000: all, 001: 회원가입, 002: 추천포인트, 003: 출석,  
004 : 동영상, 005: 좋아요, 006: 스클롤 포인트, 007: 롤업포인트
 */
  flag: string;
};
