/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface Signup {
  /** @maxLength 50 */
  username: string;
  password: string;
  email: string;
  /** @maxLength 6 */
  verification_code: string;
  /**
   * 추천한 사람의 아이디를 입력합니다.  
만약 입력하지 않을 시 빈 문자열로 입력해야 합니다.
   * @maxLength 50
   */
  referral: string;
}
