/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface UsernameCheck {
  /** @maxLength 50 */
  username: string;
  /** 사용 가능 여부 */
  readonly is_can: boolean;
}
