/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { UserForHistory } from "./userForHistory";

export interface UserSearchHistory {
  readonly id: number;
  readonly user: UserForHistory;
  /** @maxLength 120 */
  search_text: string;
  readonly create_time: string;
}
