/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface UserForHistory {
  readonly id: number;
  /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
  readonly username: string;
  /** @nullable */
  readonly last_login: string | null;
  /** @nullable */
  readonly mb_referral_id: string | null;
  readonly create_time: string;
}
