/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface UserValidationError {
  detail: string;
  /** 외부 API 에서 문제 생겼을 때만 뜹니다. */
  error_code?: string;
}
