/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { History } from "./history";

export interface UserPointHistory {
  /** 소수점의 포인트를 문자열로 표시합니다. */
  readonly total_points: string;
  /** 소수점의 포인트를 문자열로 표시합니다. */
  readonly today_points: string;
  /** 어제자 얻은 포인트 중 추천인에 의해 쌓인 포인트를 의미합니다.  
소수점의 포인트를 문자열로 표시합니다. */
  readonly yesterday_points: string;
  /** 포인트 이력을 확인합니다. */
  readonly history: readonly History[];
}
