/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { UserForHistory } from "./userForHistory";
import type { VideoForHistory } from "./videoForHistory";

export interface UserWatchHistory {
  readonly id: number;
  readonly user: UserForHistory;
  video_data_id: number;
  readonly video_data: VideoForHistory;
  start_time: string;
  /** @nullable */
  end_time?: string | null;
  readonly create_time: string;
}
