/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface UserReferralList {
  /** 1st Level 의 추천 횟수입니다. */
  readonly ret_1st: number;
  /** 2nd~20th Level 의 추천 횟수입니다. */
  readonly ret_2nd: number;
}
