/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export interface UserPoint {
  /** 소수점의 포인트를 문자열로 표시합니다. */
  readonly point: string;
}
