/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentTypeEnum } from "./contentTypeEnum";

export interface VideoForHistory {
  readonly id: number;
  readonly title: string;
  /** 유튜브, 인스타그램, 틱톡 등의 그 서비스 고유 구분자 id */
  readonly external_video_id: string;
  readonly content_type: ContentTypeEnum;
  readonly create_time: string;
}
