/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */

export type VideoDataListContentType =
  (typeof VideoDataListContentType)[keyof typeof VideoDataListContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VideoDataListContentType = {
  LONGTUBE: "LONGTUBE",
  REELS: "REELS",
  SHORTS: "SHORTS",
  TIKTOK: "TIKTOK",
} as const;
