/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import type { VideoDataListContentType } from "./videoDataListContentType";

export type VideoDataListParams = {
  /**
   * * `LONGTUBE` - 롱튜브
   * `SHORTS` - 유튜브 쇼츠
   * `REELS` - 인스타릴스
   * `TIKTOK` - 틱톡컨텐츠
   */
  content_type?: VideoDataListContentType;
  external_video_id?: string;
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A search term.
   */
  search?: string;
};
