/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * xcroll REST API
 * Welcome to xcroll Rest API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChangePassword,
  CommentListParams,
  EmailCheck,
  EmailSend,
  GetAccessToken,
  InputPoint,
  Jwt,
  LikeHistory,
  LikeHistoryListParams,
  PaginatedLikeHistoryList,
  PaginatedUserCommentsList,
  PaginatedUserList,
  PaginatedUserSearchHistoryList,
  PaginatedUserWatchHistoryList,
  PaginatedVideoDataList,
  PatchedLikeHistory,
  PatchedUserComments,
  PatchedUserSearchHistory,
  PatchedUserWatchHistory,
  PatchedVideoData,
  PointRetrieveParams,
  SearchHistoryListParams,
  SendEmailForFindPassword,
  Signup,
  TokenRefresh,
  User,
  UserComments,
  UserListParams,
  UserNameAuthRequest,
  UserPoint,
  UserPointHistory,
  UserReferralList,
  UserSearchHistory,
  UserValidationError,
  UserWatchHistory,
  UsernameCheck,
  ValidationError,
  VerifyCodeForFindPassword,
  VideoData,
  VideoDataListParams,
  WatchHistoryListParams,
} from "../model";

import { axiosInstance } from "../../../../../../src/api/instance";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

/**
 * 리프레시 토큰을 이용하여 새로운 액세스 토큰을 발급합니다.
 * @summary Get Access Token with Refresh Token
 */
export const authAuthenticateTokenRefreshCreate = (
  tokenRefresh: NonReadonly<TokenRefresh>,
  signal?: AbortSignal,
) => {
  return axiosInstance<GetAccessToken>({
    url: `/auth/authenticate/token/refresh`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tokenRefresh,
    signal,
  });
};

export const getAuthAuthenticateTokenRefreshCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationKey = ["authAuthenticateTokenRefreshCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>,
    { data: NonReadonly<TokenRefresh> }
  > = (props) => {
    const { data } = props ?? {};

    return authAuthenticateTokenRefreshCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthAuthenticateTokenRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>
>;
export type AuthAuthenticateTokenRefreshCreateMutationBody =
  NonReadonly<TokenRefresh>;
export type AuthAuthenticateTokenRefreshCreateMutationError = unknown;

/**
 * @summary Get Access Token with Refresh Token
 */
export const useAuthAuthenticateTokenRefreshCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>,
    TError,
    { data: NonReadonly<TokenRefresh> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authAuthenticateTokenRefreshCreate>>,
  TError,
  { data: NonReadonly<TokenRefresh> },
  TContext
> => {
  const mutationOptions =
    getAuthAuthenticateTokenRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Authenticate with username
 */
export const authAuthenticateUserIdCreate = (
  userNameAuthRequest: UserNameAuthRequest,
  signal?: AbortSignal,
) => {
  return axiosInstance<Jwt>({
    url: `/auth/authenticate/user-id`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userNameAuthRequest,
    signal,
  });
};

export const getAuthAuthenticateUserIdCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>,
    TError,
    { data: UserNameAuthRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>,
  TError,
  { data: UserNameAuthRequest },
  TContext
> => {
  const mutationKey = ["authAuthenticateUserIdCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>,
    { data: UserNameAuthRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authAuthenticateUserIdCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthAuthenticateUserIdCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>
>;
export type AuthAuthenticateUserIdCreateMutationBody = UserNameAuthRequest;
export type AuthAuthenticateUserIdCreateMutationError = ValidationError;

/**
 * @summary Authenticate with username
 */
export const useAuthAuthenticateUserIdCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>,
    TError,
    { data: UserNameAuthRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authAuthenticateUserIdCreate>>,
  TError,
  { data: UserNameAuthRequest },
  TContext
> => {
  const mutationOptions =
    getAuthAuthenticateUserIdCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 회원가입 시 사용하려고 하는 이메일로 받은 인증번호가 알맞는지 확인합니다.  
POST /auth/email-send 후에 사용해야 합니다.이후 POST /auth/signup API를 통해 회원가입을 진행합니다.
 * @summary 이메일 인증번호 확인
 */
export const authEmailCheckCreate = (
  emailCheck: EmailCheck,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/auth/email-check`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: emailCheck,
    signal,
  });
};

export const getAuthEmailCheckCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authEmailCheckCreate>>,
    TError,
    { data: EmailCheck },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authEmailCheckCreate>>,
  TError,
  { data: EmailCheck },
  TContext
> => {
  const mutationKey = ["authEmailCheckCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authEmailCheckCreate>>,
    { data: EmailCheck }
  > = (props) => {
    const { data } = props ?? {};

    return authEmailCheckCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthEmailCheckCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authEmailCheckCreate>>
>;
export type AuthEmailCheckCreateMutationBody = EmailCheck;
export type AuthEmailCheckCreateMutationError = ValidationError;

/**
 * @summary 이메일 인증번호 확인
 */
export const useAuthEmailCheckCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authEmailCheckCreate>>,
    TError,
    { data: EmailCheck },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authEmailCheckCreate>>,
  TError,
  { data: EmailCheck },
  TContext
> => {
  const mutationOptions = getAuthEmailCheckCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 회원가입 시 사용하려고 하는 이메일을 입력하여 인증번호를 전송합니다.  
이미 가입된 이메일인 경우 에러를 반환합니다.  
이후 POST /auth/email-check 를 통해 인증번호를 확인합니다.
 * @summary 이메일 전송
 */
export const authEmailSendCreate = (
  emailSend: EmailSend,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/auth/email-send`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: emailSend,
    signal,
  });
};

export const getAuthEmailSendCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authEmailSendCreate>>,
    TError,
    { data: EmailSend },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authEmailSendCreate>>,
  TError,
  { data: EmailSend },
  TContext
> => {
  const mutationKey = ["authEmailSendCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authEmailSendCreate>>,
    { data: EmailSend }
  > = (props) => {
    const { data } = props ?? {};

    return authEmailSendCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthEmailSendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authEmailSendCreate>>
>;
export type AuthEmailSendCreateMutationBody = EmailSend;
export type AuthEmailSendCreateMutationError = ValidationError;

/**
 * @summary 이메일 전송
 */
export const useAuthEmailSendCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authEmailSendCreate>>,
    TError,
    { data: EmailSend },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authEmailSendCreate>>,
  TError,
  { data: EmailSend },
  TContext
> => {
  const mutationOptions = getAuthEmailSendCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 비밀번호를 찾기 위해 POST /auth/find-password/email-send 를 통해 받은 인증번호를 검증합니다.  
인증번호가 유효하면 새로운 비밀번호를 이메일로 발송합니다.
 * @summary 비밀번호 찾기를 위한 인증번호 검증 + 새 비밀번호 발송
 */
export const authFindPasswordEmailCheckCreate = (
  verifyCodeForFindPassword: VerifyCodeForFindPassword,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/auth/find-password/email-check`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: verifyCodeForFindPassword,
    signal,
  });
};

export const getAuthFindPasswordEmailCheckCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>,
    TError,
    { data: VerifyCodeForFindPassword },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>,
  TError,
  { data: VerifyCodeForFindPassword },
  TContext
> => {
  const mutationKey = ["authFindPasswordEmailCheckCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>,
    { data: VerifyCodeForFindPassword }
  > = (props) => {
    const { data } = props ?? {};

    return authFindPasswordEmailCheckCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthFindPasswordEmailCheckCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>
>;
export type AuthFindPasswordEmailCheckCreateMutationBody =
  VerifyCodeForFindPassword;
export type AuthFindPasswordEmailCheckCreateMutationError = ValidationError;

/**
 * @summary 비밀번호 찾기를 위한 인증번호 검증 + 새 비밀번호 발송
 */
export const useAuthFindPasswordEmailCheckCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>,
    TError,
    { data: VerifyCodeForFindPassword },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authFindPasswordEmailCheckCreate>>,
  TError,
  { data: VerifyCodeForFindPassword },
  TContext
> => {
  const mutationOptions =
    getAuthFindPasswordEmailCheckCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 비밀번호를 찾기 위해 가입한 이메일로 인증번호를 발송합니다.
 * @summary 비밀번호 찾기를 위한 인증번호 이메일 발송
 */
export const authFindPasswordEmailSendCreate = (
  sendEmailForFindPassword: SendEmailForFindPassword,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/auth/find-password/email-send`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: sendEmailForFindPassword,
    signal,
  });
};

export const getAuthFindPasswordEmailSendCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>,
    TError,
    { data: SendEmailForFindPassword },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>,
  TError,
  { data: SendEmailForFindPassword },
  TContext
> => {
  const mutationKey = ["authFindPasswordEmailSendCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>,
    { data: SendEmailForFindPassword }
  > = (props) => {
    const { data } = props ?? {};

    return authFindPasswordEmailSendCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthFindPasswordEmailSendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>
>;
export type AuthFindPasswordEmailSendCreateMutationBody =
  SendEmailForFindPassword;
export type AuthFindPasswordEmailSendCreateMutationError = ValidationError;

/**
 * @summary 비밀번호 찾기를 위한 인증번호 이메일 발송
 */
export const useAuthFindPasswordEmailSendCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>,
    TError,
    { data: SendEmailForFindPassword },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authFindPasswordEmailSendCreate>>,
  TError,
  { data: SendEmailForFindPassword },
  TContext
> => {
  const mutationOptions =
    getAuthFindPasswordEmailSendCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 회원가입을 진행합니다.  
POST auth/email 시리즈, POST /auth/username-check 를 한 뒤에 사용해야 합니다.
 * @summary 회원가입
 */
export const authSignupCreate = (signup: Signup, signal?: AbortSignal) => {
  return axiosInstance<Signup>({
    url: `/auth/signup`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: signup,
    signal,
  });
};

export const getAuthSignupCreateMutationOptions = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authSignupCreate>>,
    TError,
    { data: Signup },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authSignupCreate>>,
  TError,
  { data: Signup },
  TContext
> => {
  const mutationKey = ["authSignupCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authSignupCreate>>,
    { data: Signup }
  > = (props) => {
    const { data } = props ?? {};

    return authSignupCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthSignupCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authSignupCreate>>
>;
export type AuthSignupCreateMutationBody = Signup;
export type AuthSignupCreateMutationError = ValidationError;

/**
 * @summary 회원가입
 */
export const useAuthSignupCreate = <
  TError = ValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authSignupCreate>>,
    TError,
    { data: Signup },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authSignupCreate>>,
  TError,
  { data: Signup },
  TContext
> => {
  const mutationOptions = getAuthSignupCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 회원가입 시 사용하려고 하는 아이디를 입력하여 사용 가능 여부를 확인합니다.  
사용 가능한 아이디인 경우 is_can: true 를 반환합니다.
 * @summary 아이디 중복 확인
 */
export const authUsernameCheckCreate = (
  usernameCheck: NonReadonly<UsernameCheck>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UsernameCheck>({
    url: `/auth/username-check`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: usernameCheck,
    signal,
  });
};

export const getAuthUsernameCheckCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsernameCheckCreate>>,
    TError,
    { data: NonReadonly<UsernameCheck> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsernameCheckCreate>>,
  TError,
  { data: NonReadonly<UsernameCheck> },
  TContext
> => {
  const mutationKey = ["authUsernameCheckCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsernameCheckCreate>>,
    { data: NonReadonly<UsernameCheck> }
  > = (props) => {
    const { data } = props ?? {};

    return authUsernameCheckCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsernameCheckCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsernameCheckCreate>>
>;
export type AuthUsernameCheckCreateMutationBody = NonReadonly<UsernameCheck>;
export type AuthUsernameCheckCreateMutationError = unknown;

/**
 * @summary 아이디 중복 확인
 */
export const useAuthUsernameCheckCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsernameCheckCreate>>,
    TError,
    { data: NonReadonly<UsernameCheck> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authUsernameCheckCreate>>,
  TError,
  { data: NonReadonly<UsernameCheck> },
  TContext
> => {
  const mutationOptions = getAuthUsernameCheckCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 댓글 리스트를 조회합니다.  
삭제된 댓글은 상황에 따라 content 값이 '삭제된 댓글입니다.'라고 텍스트 대치 처리가 되며 user 값이 null 처리됩니다.  
* 대댓글아 삭제됐을 경우  
  * 텍스트 대치 처리가 됩니다.  
* 부모 댓글이 삭제됐을 경우  
  * 대댓글이 없을 경우엔 조회되지 않습니다.  
  * 대댓글이 있을 경우 텍스트 대치 처리가 됩니다.  
filter 로 유저 아이디, 비디오 아이디, 대댓글이 아닌 댓글 유무, 대댓글의 부모 댓글 id 를 사용할 수 있습니다.  
* 대댓글 조회 시 parent_id 를 사용합니다.  
* 부모 댓글 조회 시 is_parent 를 true 로 지정합니다.  
특정 비디오의 댓글을 조회할 땐 is_parent 를 true 로 지정하고 video_data id 를 사용합니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get Comments List
 */
export const commentList = (
  params?: CommentListParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedUserCommentsList>({
    url: `/comment`,
    method: "GET",
    params,
    signal,
  });
};

export const getCommentListQueryKey = (params?: CommentListParams) => {
  return [`/comment`, ...(params ? [params] : [])] as const;
};

export const getCommentListQueryOptions = <
  TData = Awaited<ReturnType<typeof commentList>>,
  TError = unknown,
>(
  params?: CommentListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof commentList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCommentListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof commentList>>> = ({
    signal,
  }) => commentList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof commentList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CommentListQueryResult = NonNullable<
  Awaited<ReturnType<typeof commentList>>
>;
export type CommentListQueryError = unknown;

/**
 * @summary Get Comments List
 */

export function useCommentList<
  TData = Awaited<ReturnType<typeof commentList>>,
  TError = unknown,
>(
  params?: CommentListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof commentList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCommentListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 댓글을 작성합니다.  
대댓글을 작성할 시 parent_id 를 지정합니다.
 * @summary Create Comments
 */
export const commentCreate = (
  userComments: NonReadonly<UserComments>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UserComments>({
    url: `/comment`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userComments,
    signal,
  });
};

export const getCommentCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentCreate>>,
    TError,
    { data: NonReadonly<UserComments> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof commentCreate>>,
  TError,
  { data: NonReadonly<UserComments> },
  TContext
> => {
  const mutationKey = ["commentCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentCreate>>,
    { data: NonReadonly<UserComments> }
  > = (props) => {
    const { data } = props ?? {};

    return commentCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentCreate>>
>;
export type CommentCreateMutationBody = NonReadonly<UserComments>;
export type CommentCreateMutationError = unknown;

/**
 * @summary Create Comments
 */
export const useCommentCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentCreate>>,
    TError,
    { data: NonReadonly<UserComments> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof commentCreate>>,
  TError,
  { data: NonReadonly<UserComments> },
  TContext
> => {
  const mutationOptions = getCommentCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 댓글을 조회합니다.
 * @summary Get Comment Detail
 */
export const commentRetrieve = (id: number, signal?: AbortSignal) => {
  return axiosInstance<UserComments>({
    url: `/comment/${id}`,
    method: "GET",
    signal,
  });
};

export const getCommentRetrieveQueryKey = (id: number) => {
  return [`/comment/${id}`] as const;
};

export const getCommentRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof commentRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof commentRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCommentRetrieveQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof commentRetrieve>>> = ({
    signal,
  }) => commentRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof commentRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CommentRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof commentRetrieve>>
>;
export type CommentRetrieveQueryError = unknown;

/**
 * @summary Get Comment Detail
 */

export function useCommentRetrieve<
  TData = Awaited<ReturnType<typeof commentRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof commentRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCommentRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 댓글을 수정합니다.  
본인의 댓글만 수정할 수 있습니다.
 * @summary Update Comment
 */
export const commentPartialUpdate = (
  id: number,
  patchedUserComments: NonReadonly<PatchedUserComments>,
) => {
  return axiosInstance<UserComments>({
    url: `/comment/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedUserComments,
  });
};

export const getCommentPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserComments> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof commentPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserComments> },
  TContext
> => {
  const mutationKey = ["commentPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedUserComments> }
  > = (props) => {
    const { id, data } = props ?? {};

    return commentPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentPartialUpdate>>
>;
export type CommentPartialUpdateMutationBody = NonReadonly<PatchedUserComments>;
export type CommentPartialUpdateMutationError = unknown;

/**
 * @summary Update Comment
 */
export const useCommentPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserComments> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof commentPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserComments> },
  TContext
> => {
  const mutationOptions = getCommentPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 댓글을 삭제합니다.  
본인의 댓글만 삭제할 수 있습니다.
 * @summary Delete Comment
 */
export const commentDestroy = (id: number) => {
  return axiosInstance<void>({ url: `/comment/${id}`, method: "DELETE" });
};

export const getCommentDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof commentDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["commentDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return commentDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentDestroy>>
>;

export type CommentDestroyMutationError = unknown;

/**
 * @summary Delete Comment
 */
export const useCommentDestroy = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof commentDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof commentDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCommentDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 좋아요 기록 리스트를 조회합니다.  
filter 로 유저 아이디를 사용할 수 있습니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get Like History List
 */
export const likeHistoryList = (
  params?: LikeHistoryListParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedLikeHistoryList>({
    url: `/like-history`,
    method: "GET",
    params,
    signal,
  });
};

export const getLikeHistoryListQueryKey = (params?: LikeHistoryListParams) => {
  return [`/like-history`, ...(params ? [params] : [])] as const;
};

export const getLikeHistoryListQueryOptions = <
  TData = Awaited<ReturnType<typeof likeHistoryList>>,
  TError = unknown,
>(
  params?: LikeHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof likeHistoryList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLikeHistoryListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof likeHistoryList>>> = ({
    signal,
  }) => likeHistoryList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof likeHistoryList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type LikeHistoryListQueryResult = NonNullable<
  Awaited<ReturnType<typeof likeHistoryList>>
>;
export type LikeHistoryListQueryError = unknown;

/**
 * @summary Get Like History List
 */

export function useLikeHistoryList<
  TData = Awaited<ReturnType<typeof likeHistoryList>>,
  TError = unknown,
>(
  params?: LikeHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof likeHistoryList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getLikeHistoryListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 좋아요 기록을 생성합니다.
 * @summary Create Like History
 */
export const likeHistoryCreate = (
  likeHistory: NonReadonly<LikeHistory>,
  signal?: AbortSignal,
) => {
  return axiosInstance<LikeHistory>({
    url: `/like-history`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: likeHistory,
    signal,
  });
};

export const getLikeHistoryCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryCreate>>,
    TError,
    { data: NonReadonly<LikeHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeHistoryCreate>>,
  TError,
  { data: NonReadonly<LikeHistory> },
  TContext
> => {
  const mutationKey = ["likeHistoryCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeHistoryCreate>>,
    { data: NonReadonly<LikeHistory> }
  > = (props) => {
    const { data } = props ?? {};

    return likeHistoryCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeHistoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeHistoryCreate>>
>;
export type LikeHistoryCreateMutationBody = NonReadonly<LikeHistory>;
export type LikeHistoryCreateMutationError = unknown;

/**
 * @summary Create Like History
 */
export const useLikeHistoryCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryCreate>>,
    TError,
    { data: NonReadonly<LikeHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof likeHistoryCreate>>,
  TError,
  { data: NonReadonly<LikeHistory> },
  TContext
> => {
  const mutationOptions = getLikeHistoryCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 좋아요 기록을 조회합니다.
 * @summary Get Like History Detail
 */
export const likeHistoryRetrieve = (id: number, signal?: AbortSignal) => {
  return axiosInstance<LikeHistory>({
    url: `/like-history/${id}`,
    method: "GET",
    signal,
  });
};

export const getLikeHistoryRetrieveQueryKey = (id: number) => {
  return [`/like-history/${id}`] as const;
};

export const getLikeHistoryRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof likeHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof likeHistoryRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLikeHistoryRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof likeHistoryRetrieve>>
  > = ({ signal }) => likeHistoryRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof likeHistoryRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type LikeHistoryRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof likeHistoryRetrieve>>
>;
export type LikeHistoryRetrieveQueryError = unknown;

/**
 * @summary Get Like History Detail
 */

export function useLikeHistoryRetrieve<
  TData = Awaited<ReturnType<typeof likeHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof likeHistoryRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getLikeHistoryRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 좋아요 기록을 수정합니다.  
본인의 좋아요 기록만 수정할 수 있습니다.
 * @summary Update Like History
 */
export const likeHistoryPartialUpdate = (
  id: number,
  patchedLikeHistory: NonReadonly<PatchedLikeHistory>,
) => {
  return axiosInstance<LikeHistory>({
    url: `/like-history/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedLikeHistory,
  });
};

export const getLikeHistoryPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedLikeHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedLikeHistory> },
  TContext
> => {
  const mutationKey = ["likeHistoryPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeHistoryPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedLikeHistory> }
  > = (props) => {
    const { id, data } = props ?? {};

    return likeHistoryPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeHistoryPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeHistoryPartialUpdate>>
>;
export type LikeHistoryPartialUpdateMutationBody =
  NonReadonly<PatchedLikeHistory>;
export type LikeHistoryPartialUpdateMutationError = unknown;

/**
 * @summary Update Like History
 */
export const useLikeHistoryPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedLikeHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof likeHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedLikeHistory> },
  TContext
> => {
  const mutationOptions = getLikeHistoryPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 좋아요 기록을 삭제합니다.  
본인의 좋아요 기록만 삭제할 수 있습니다.
 * @summary Delete Like History
 */
export const likeHistoryDestroy = (id: number) => {
  return axiosInstance<void>({ url: `/like-history/${id}`, method: "DELETE" });
};

export const getLikeHistoryDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeHistoryDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["likeHistoryDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeHistoryDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return likeHistoryDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeHistoryDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeHistoryDestroy>>
>;

export type LikeHistoryDestroyMutationError = unknown;

/**
 * @summary Delete Like History
 */
export const useLikeHistoryDestroy = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeHistoryDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof likeHistoryDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getLikeHistoryDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 상황에 따른 포인트를 입금합니다.
 * @summary 포인트 입금
 */
export const pointCreate = (inputPoint: InputPoint, signal?: AbortSignal) => {
  return axiosInstance<void>({
    url: `/point`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: inputPoint,
    signal,
  });
};

export const getPointCreateMutationOptions = <
  TError = UserValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pointCreate>>,
    TError,
    { data: InputPoint },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pointCreate>>,
  TError,
  { data: InputPoint },
  TContext
> => {
  const mutationKey = ["pointCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pointCreate>>,
    { data: InputPoint }
  > = (props) => {
    const { data } = props ?? {};

    return pointCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PointCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof pointCreate>>
>;
export type PointCreateMutationBody = InputPoint;
export type PointCreateMutationError = UserValidationError;

/**
 * @summary 포인트 입금
 */
export const usePointCreate = <
  TError = UserValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pointCreate>>,
    TError,
    { data: InputPoint },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof pointCreate>>,
  TError,
  { data: InputPoint },
  TContext
> => {
  const mutationOptions = getPointCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 현재 포인트를 확인합니다.  
**me** Path Parameter 를 사용하면 현재 로그인한 유저의 포인트를 확인할 수 있습니다.  
오늘자, 어제자 얻은 포인트는 /post 에서 확인할 수 있습니다.
 * @summary 내 포인트 조회
 */
export const pointRetrieve = (
  id: string,
  params: PointRetrieveParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<UserPoint>({
    url: `/point/${id}`,
    method: "GET",
    params,
    signal,
  });
};

export const getPointRetrieveQueryKey = (
  id: string,
  params: PointRetrieveParams,
) => {
  return [`/point/${id}`, ...(params ? [params] : [])] as const;
};

export const getPointRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof pointRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  params: PointRetrieveParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof pointRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPointRetrieveQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof pointRetrieve>>> = ({
    signal,
  }) => pointRetrieve(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof pointRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PointRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof pointRetrieve>>
>;
export type PointRetrieveQueryError = UserValidationError;

/**
 * @summary 내 포인트 조회
 */

export function usePointRetrieve<
  TData = Awaited<ReturnType<typeof pointRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  params: PointRetrieveParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof pointRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPointRetrieveQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 오늘자, 어제자 얻은 포인트와 더불어 포인트 이력을 확인합니다.
 **me** Path Parameter 를 사용하면 현재 로그인한 유저의 포인트 이력을 확인할 수 있습니다.
 * @summary 포인트 이력/최근 2일 얻은 포인트 조회
 */
export const pointHistoryRetrieve = (id: string, signal?: AbortSignal) => {
  return axiosInstance<UserPointHistory>({
    url: `/point/history/${id}`,
    method: "GET",
    signal,
  });
};

export const getPointHistoryRetrieveQueryKey = (id: string) => {
  return [`/point/history/${id}`] as const;
};

export const getPointHistoryRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof pointHistoryRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof pointHistoryRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPointHistoryRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pointHistoryRetrieve>>
  > = ({ signal }) => pointHistoryRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof pointHistoryRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PointHistoryRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof pointHistoryRetrieve>>
>;
export type PointHistoryRetrieveQueryError = UserValidationError;

/**
 * @summary 포인트 이력/최근 2일 얻은 포인트 조회
 */

export function usePointHistoryRetrieve<
  TData = Awaited<ReturnType<typeof pointHistoryRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof pointHistoryRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPointHistoryRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 유저 검색 기록 리스트를 조회합니다.  
filter 로 유저 아이디를 사용할 수 있습니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get User Search History List
 */
export const searchHistoryList = (
  params?: SearchHistoryListParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedUserSearchHistoryList>({
    url: `/search-history`,
    method: "GET",
    params,
    signal,
  });
};

export const getSearchHistoryListQueryKey = (
  params?: SearchHistoryListParams,
) => {
  return [`/search-history`, ...(params ? [params] : [])] as const;
};

export const getSearchHistoryListQueryOptions = <
  TData = Awaited<ReturnType<typeof searchHistoryList>>,
  TError = unknown,
>(
  params?: SearchHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchHistoryList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchHistoryListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchHistoryList>>
  > = ({ signal }) => searchHistoryList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchHistoryList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchHistoryListQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchHistoryList>>
>;
export type SearchHistoryListQueryError = unknown;

/**
 * @summary Get User Search History List
 */

export function useSearchHistoryList<
  TData = Awaited<ReturnType<typeof searchHistoryList>>,
  TError = unknown,
>(
  params?: SearchHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchHistoryList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchHistoryListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 유저의 검색 기록을 생성합니다.
 * @summary Create User Search History
 */
export const searchHistoryCreate = (
  userSearchHistory: NonReadonly<UserSearchHistory>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UserSearchHistory>({
    url: `/search-history`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userSearchHistory,
    signal,
  });
};

export const getSearchHistoryCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryCreate>>,
    TError,
    { data: NonReadonly<UserSearchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchHistoryCreate>>,
  TError,
  { data: NonReadonly<UserSearchHistory> },
  TContext
> => {
  const mutationKey = ["searchHistoryCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchHistoryCreate>>,
    { data: NonReadonly<UserSearchHistory> }
  > = (props) => {
    const { data } = props ?? {};

    return searchHistoryCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchHistoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchHistoryCreate>>
>;
export type SearchHistoryCreateMutationBody = NonReadonly<UserSearchHistory>;
export type SearchHistoryCreateMutationError = unknown;

/**
 * @summary Create User Search History
 */
export const useSearchHistoryCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryCreate>>,
    TError,
    { data: NonReadonly<UserSearchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof searchHistoryCreate>>,
  TError,
  { data: NonReadonly<UserSearchHistory> },
  TContext
> => {
  const mutationOptions = getSearchHistoryCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 유저의 검색 기록을 조회합니다.
 * @summary Get User Search History Detail
 */
export const searchHistoryRetrieve = (id: number, signal?: AbortSignal) => {
  return axiosInstance<UserSearchHistory>({
    url: `/search-history/${id}`,
    method: "GET",
    signal,
  });
};

export const getSearchHistoryRetrieveQueryKey = (id: number) => {
  return [`/search-history/${id}`] as const;
};

export const getSearchHistoryRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof searchHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchHistoryRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchHistoryRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchHistoryRetrieve>>
  > = ({ signal }) => searchHistoryRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof searchHistoryRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchHistoryRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchHistoryRetrieve>>
>;
export type SearchHistoryRetrieveQueryError = unknown;

/**
 * @summary Get User Search History Detail
 */

export function useSearchHistoryRetrieve<
  TData = Awaited<ReturnType<typeof searchHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchHistoryRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchHistoryRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const searchHistoryUpdate = (
  id: number,
  userSearchHistory: NonReadonly<UserSearchHistory>,
) => {
  return axiosInstance<UserSearchHistory>({
    url: `/search-history/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: userSearchHistory,
  });
};

export const getSearchHistoryUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryUpdate>>,
    TError,
    { id: number; data: NonReadonly<UserSearchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchHistoryUpdate>>,
  TError,
  { id: number; data: NonReadonly<UserSearchHistory> },
  TContext
> => {
  const mutationKey = ["searchHistoryUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchHistoryUpdate>>,
    { id: number; data: NonReadonly<UserSearchHistory> }
  > = (props) => {
    const { id, data } = props ?? {};

    return searchHistoryUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchHistoryUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchHistoryUpdate>>
>;
export type SearchHistoryUpdateMutationBody = NonReadonly<UserSearchHistory>;
export type SearchHistoryUpdateMutationError = unknown;

export const useSearchHistoryUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryUpdate>>,
    TError,
    { id: number; data: NonReadonly<UserSearchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof searchHistoryUpdate>>,
  TError,
  { id: number; data: NonReadonly<UserSearchHistory> },
  TContext
> => {
  const mutationOptions = getSearchHistoryUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 유저의 검색 기록을 수정합니다.  
본인의 검색 기록만 수정할 수 있습니다.
 * @summary Update User Search History
 */
export const searchHistoryPartialUpdate = (
  id: number,
  patchedUserSearchHistory: NonReadonly<PatchedUserSearchHistory>,
) => {
  return axiosInstance<UserSearchHistory>({
    url: `/search-history/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedUserSearchHistory,
  });
};

export const getSearchHistoryPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserSearchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserSearchHistory> },
  TContext
> => {
  const mutationKey = ["searchHistoryPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchHistoryPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedUserSearchHistory> }
  > = (props) => {
    const { id, data } = props ?? {};

    return searchHistoryPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchHistoryPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof searchHistoryPartialUpdate>>
>;
export type SearchHistoryPartialUpdateMutationBody =
  NonReadonly<PatchedUserSearchHistory>;
export type SearchHistoryPartialUpdateMutationError = unknown;

/**
 * @summary Update User Search History
 */
export const useSearchHistoryPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserSearchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof searchHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserSearchHistory> },
  TContext
> => {
  const mutationOptions = getSearchHistoryPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 유저 리스트를 조회합니다.  
search 로 유저 아이디를 검색할 수 있습니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get User List
 */
export const userList = (params?: UserListParams, signal?: AbortSignal) => {
  return axiosInstance<PaginatedUserList>({
    url: `/user`,
    method: "GET",
    params,
    signal,
  });
};

export const getUserListQueryKey = (params?: UserListParams) => {
  return [`/user`, ...(params ? [params] : [])] as const;
};

export const getUserListQueryOptions = <
  TData = Awaited<ReturnType<typeof userList>>,
  TError = unknown,
>(
  params?: UserListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userList>>> = ({
    signal,
  }) => userList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserListQueryResult = NonNullable<
  Awaited<ReturnType<typeof userList>>
>;
export type UserListQueryError = unknown;

/**
 * @summary Get User List
 */

export function useUserList<
  TData = Awaited<ReturnType<typeof userList>>,
  TError = unknown,
>(
  params?: UserListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 유저의 상세 정보를 조회합니다.
 **me** Path Parameter 를 사용하면 현재 로그인한 유저의 정보를 조회할 수 있습니다.
 * @summary Get User Detail
 */
export const userRetrieve = (id: string, signal?: AbortSignal) => {
  return axiosInstance<User>({ url: `/user/${id}`, method: "GET", signal });
};

export const getUserRetrieveQueryKey = (id: string) => {
  return [`/user/${id}`] as const;
};

export const getUserRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof userRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserRetrieveQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userRetrieve>>> = ({
    signal,
  }) => userRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof userRetrieve>>
>;
export type UserRetrieveQueryError = unknown;

/**
 * @summary Get User Detail
 */

export function useUserRetrieve<
  TData = Awaited<ReturnType<typeof userRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 회원 탈퇴합니다. **me** Path Parameter 로 본인만 가능합니다.
 * @summary 회원 탈퇴
 */
export const userDestroy = (id: string) => {
  return axiosInstance<void>({ url: `/user/${id}`, method: "DELETE" });
};

export const getUserDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userDestroy>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["userDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userDestroy>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof userDestroy>>
>;

export type UserDestroyMutationError = unknown;

/**
 * @summary 회원 탈퇴
 */
export const useUserDestroy = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userDestroy>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUserDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 비밀번호를 변경합니다.  
기존 비밀번호와 더불어 신규 비밀번호를 같이 입력해야 합니다.
 * @summary 비밀번호 변경
 */
export const userChangePasswordCreate = (
  changePassword: ChangePassword,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>({
    url: `/user/change-password`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: changePassword,
    signal,
  });
};

export const getUserChangePasswordCreateMutationOptions = <
  TError = UserValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userChangePasswordCreate>>,
    TError,
    { data: ChangePassword },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userChangePasswordCreate>>,
  TError,
  { data: ChangePassword },
  TContext
> => {
  const mutationKey = ["userChangePasswordCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userChangePasswordCreate>>,
    { data: ChangePassword }
  > = (props) => {
    const { data } = props ?? {};

    return userChangePasswordCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserChangePasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userChangePasswordCreate>>
>;
export type UserChangePasswordCreateMutationBody = ChangePassword;
export type UserChangePasswordCreateMutationError = UserValidationError;

/**
 * @summary 비밀번호 변경
 */
export const useUserChangePasswordCreate = <
  TError = UserValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userChangePasswordCreate>>,
    TError,
    { data: ChangePassword },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof userChangePasswordCreate>>,
  TError,
  { data: ChangePassword },
  TContext
> => {
  const mutationOptions = getUserChangePasswordCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 내 추천 횟수 리스트를 조회합니다.
 **me** Path Parameter 를 사용하면 현재 로그인한 유저의 추천 횟수 리스트를 조회할 수 있습니다.
 * @summary 내 추천 횟수 조회
 */
export const userReferralListRetrieve = (id: string, signal?: AbortSignal) => {
  return axiosInstance<UserReferralList>({
    url: `/user/referral-list/${id}`,
    method: "GET",
    signal,
  });
};

export const getUserReferralListRetrieveQueryKey = (id: string) => {
  return [`/user/referral-list/${id}`] as const;
};

export const getUserReferralListRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof userReferralListRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userReferralListRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserReferralListRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userReferralListRetrieve>>
  > = ({ signal }) => userReferralListRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userReferralListRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UserReferralListRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof userReferralListRetrieve>>
>;
export type UserReferralListRetrieveQueryError = UserValidationError;

/**
 * @summary 내 추천 횟수 조회
 */

export function useUserReferralListRetrieve<
  TData = Awaited<ReturnType<typeof userReferralListRetrieve>>,
  TError = UserValidationError,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof userReferralListRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUserReferralListRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 비디오 리스트를 조회합니다.  
content_type 으로 필터링 가능합니다.  
search 로 영상 이름, 영상 설명을 검색할 수 있습니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get Video Data List
 */
export const videoDataList = (
  params?: VideoDataListParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedVideoDataList>({
    url: `/video-data`,
    method: "GET",
    params,
    signal,
  });
};

export const getVideoDataListQueryKey = (params?: VideoDataListParams) => {
  return [`/video-data`, ...(params ? [params] : [])] as const;
};

export const getVideoDataListQueryOptions = <
  TData = Awaited<ReturnType<typeof videoDataList>>,
  TError = unknown,
>(
  params?: VideoDataListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof videoDataList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVideoDataListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof videoDataList>>> = ({
    signal,
  }) => videoDataList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof videoDataList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type VideoDataListQueryResult = NonNullable<
  Awaited<ReturnType<typeof videoDataList>>
>;
export type VideoDataListQueryError = unknown;

/**
 * @summary Get Video Data List
 */

export function useVideoDataList<
  TData = Awaited<ReturnType<typeof videoDataList>>,
  TError = unknown,
>(
  params?: VideoDataListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof videoDataList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getVideoDataListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 새로운 비디오 데이터를 생성합니다.
 * @summary Create Video Data
 */
export const videoDataCreate = (
  videoData: NonReadonly<VideoData>,
  signal?: AbortSignal,
) => {
  return axiosInstance<VideoData>({
    url: `/video-data`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: videoData,
    signal,
  });
};

export const getVideoDataCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataCreate>>,
    TError,
    { data: NonReadonly<VideoData> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof videoDataCreate>>,
  TError,
  { data: NonReadonly<VideoData> },
  TContext
> => {
  const mutationKey = ["videoDataCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof videoDataCreate>>,
    { data: NonReadonly<VideoData> }
  > = (props) => {
    const { data } = props ?? {};

    return videoDataCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VideoDataCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof videoDataCreate>>
>;
export type VideoDataCreateMutationBody = NonReadonly<VideoData>;
export type VideoDataCreateMutationError = unknown;

/**
 * @summary Create Video Data
 */
export const useVideoDataCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataCreate>>,
    TError,
    { data: NonReadonly<VideoData> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof videoDataCreate>>,
  TError,
  { data: NonReadonly<VideoData> },
  TContext
> => {
  const mutationOptions = getVideoDataCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 비디오의 상세 정보를 조회합니다.
 * @summary Get Video Data Detail
 */
export const videoDataRetrieve = (id: number, signal?: AbortSignal) => {
  return axiosInstance<VideoData>({
    url: `/video-data/${id}`,
    method: "GET",
    signal,
  });
};

export const getVideoDataRetrieveQueryKey = (id: number) => {
  return [`/video-data/${id}`] as const;
};

export const getVideoDataRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof videoDataRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof videoDataRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVideoDataRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof videoDataRetrieve>>
  > = ({ signal }) => videoDataRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof videoDataRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type VideoDataRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof videoDataRetrieve>>
>;
export type VideoDataRetrieveQueryError = unknown;

/**
 * @summary Get Video Data Detail
 */

export function useVideoDataRetrieve<
  TData = Awaited<ReturnType<typeof videoDataRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof videoDataRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getVideoDataRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 비디오의 정보를 수정합니다.
 * @summary Update Video Data
 */
export const videoDataPartialUpdate = (
  id: number,
  patchedVideoData: NonReadonly<PatchedVideoData>,
) => {
  return axiosInstance<VideoData>({
    url: `/video-data/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedVideoData,
  });
};

export const getVideoDataPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedVideoData> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof videoDataPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedVideoData> },
  TContext
> => {
  const mutationKey = ["videoDataPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof videoDataPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedVideoData> }
  > = (props) => {
    const { id, data } = props ?? {};

    return videoDataPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VideoDataPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof videoDataPartialUpdate>>
>;
export type VideoDataPartialUpdateMutationBody = NonReadonly<PatchedVideoData>;
export type VideoDataPartialUpdateMutationError = unknown;

/**
 * @summary Update Video Data
 */
export const useVideoDataPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedVideoData> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof videoDataPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedVideoData> },
  TContext
> => {
  const mutationOptions = getVideoDataPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 비디오를 삭제합니다.  
마스터 계정만 가능합니다.
 * @summary Delete Video Data
 */
export const videoDataDestroy = (id: number) => {
  return axiosInstance<void>({ url: `/video-data/${id}`, method: "DELETE" });
};

export const getVideoDataDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof videoDataDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["videoDataDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof videoDataDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return videoDataDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VideoDataDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof videoDataDestroy>>
>;

export type VideoDataDestroyMutationError = unknown;

/**
 * @summary Delete Video Data
 */
export const useVideoDataDestroy = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof videoDataDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof videoDataDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getVideoDataDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 유저 시청 기록 리스트를 조회합니다.  
filter 로 유저 아이디를 사용할 수 있습니다.  
ordering 으로 id, create_time 으로 정렬할 수 있습니다. 최신순(내림차순)은 -create_time 입니다.
 * @summary Get User Watch History List
 */
export const watchHistoryList = (
  params?: WatchHistoryListParams,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedUserWatchHistoryList>({
    url: `/watch-history`,
    method: "GET",
    params,
    signal,
  });
};

export const getWatchHistoryListQueryKey = (
  params?: WatchHistoryListParams,
) => {
  return [`/watch-history`, ...(params ? [params] : [])] as const;
};

export const getWatchHistoryListQueryOptions = <
  TData = Awaited<ReturnType<typeof watchHistoryList>>,
  TError = unknown,
>(
  params?: WatchHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof watchHistoryList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWatchHistoryListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof watchHistoryList>>
  > = ({ signal }) => watchHistoryList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof watchHistoryList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WatchHistoryListQueryResult = NonNullable<
  Awaited<ReturnType<typeof watchHistoryList>>
>;
export type WatchHistoryListQueryError = unknown;

/**
 * @summary Get User Watch History List
 */

export function useWatchHistoryList<
  TData = Awaited<ReturnType<typeof watchHistoryList>>,
  TError = unknown,
>(
  params?: WatchHistoryListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof watchHistoryList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getWatchHistoryListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 유저의 시청 기록을 생성합니다.
 * @summary Create User Watch History
 */
export const watchHistoryCreate = (
  userWatchHistory: NonReadonly<UserWatchHistory>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UserWatchHistory>({
    url: `/watch-history`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userWatchHistory,
    signal,
  });
};

export const getWatchHistoryCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryCreate>>,
    TError,
    { data: NonReadonly<UserWatchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof watchHistoryCreate>>,
  TError,
  { data: NonReadonly<UserWatchHistory> },
  TContext
> => {
  const mutationKey = ["watchHistoryCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof watchHistoryCreate>>,
    { data: NonReadonly<UserWatchHistory> }
  > = (props) => {
    const { data } = props ?? {};

    return watchHistoryCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type WatchHistoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof watchHistoryCreate>>
>;
export type WatchHistoryCreateMutationBody = NonReadonly<UserWatchHistory>;
export type WatchHistoryCreateMutationError = unknown;

/**
 * @summary Create User Watch History
 */
export const useWatchHistoryCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryCreate>>,
    TError,
    { data: NonReadonly<UserWatchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof watchHistoryCreate>>,
  TError,
  { data: NonReadonly<UserWatchHistory> },
  TContext
> => {
  const mutationOptions = getWatchHistoryCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 유저 시청 기록을 조회합니다.
 * @summary Get User Watch History Detail
 */
export const watchHistoryRetrieve = (id: number, signal?: AbortSignal) => {
  return axiosInstance<UserWatchHistory>({
    url: `/watch-history/${id}`,
    method: "GET",
    signal,
  });
};

export const getWatchHistoryRetrieveQueryKey = (id: number) => {
  return [`/watch-history/${id}`] as const;
};

export const getWatchHistoryRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof watchHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof watchHistoryRetrieve>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWatchHistoryRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof watchHistoryRetrieve>>
  > = ({ signal }) => watchHistoryRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof watchHistoryRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WatchHistoryRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof watchHistoryRetrieve>>
>;
export type WatchHistoryRetrieveQueryError = unknown;

/**
 * @summary Get User Watch History Detail
 */

export function useWatchHistoryRetrieve<
  TData = Awaited<ReturnType<typeof watchHistoryRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof watchHistoryRetrieve>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getWatchHistoryRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const watchHistoryUpdate = (
  id: number,
  userWatchHistory: NonReadonly<UserWatchHistory>,
) => {
  return axiosInstance<UserWatchHistory>({
    url: `/watch-history/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: userWatchHistory,
  });
};

export const getWatchHistoryUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryUpdate>>,
    TError,
    { id: number; data: NonReadonly<UserWatchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof watchHistoryUpdate>>,
  TError,
  { id: number; data: NonReadonly<UserWatchHistory> },
  TContext
> => {
  const mutationKey = ["watchHistoryUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof watchHistoryUpdate>>,
    { id: number; data: NonReadonly<UserWatchHistory> }
  > = (props) => {
    const { id, data } = props ?? {};

    return watchHistoryUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type WatchHistoryUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof watchHistoryUpdate>>
>;
export type WatchHistoryUpdateMutationBody = NonReadonly<UserWatchHistory>;
export type WatchHistoryUpdateMutationError = unknown;

export const useWatchHistoryUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryUpdate>>,
    TError,
    { id: number; data: NonReadonly<UserWatchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof watchHistoryUpdate>>,
  TError,
  { id: number; data: NonReadonly<UserWatchHistory> },
  TContext
> => {
  const mutationOptions = getWatchHistoryUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * 특정 유저 시청 기록을 수정합니다.  
본인의 시청 기록만 수정할 수 있습니다.
 * @summary Update User Watch History
 */
export const watchHistoryPartialUpdate = (
  id: number,
  patchedUserWatchHistory: NonReadonly<PatchedUserWatchHistory>,
) => {
  return axiosInstance<UserWatchHistory>({
    url: `/watch-history/${id}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedUserWatchHistory,
  });
};

export const getWatchHistoryPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserWatchHistory> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof watchHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserWatchHistory> },
  TContext
> => {
  const mutationKey = ["watchHistoryPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof watchHistoryPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedUserWatchHistory> }
  > = (props) => {
    const { id, data } = props ?? {};

    return watchHistoryPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type WatchHistoryPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof watchHistoryPartialUpdate>>
>;
export type WatchHistoryPartialUpdateMutationBody =
  NonReadonly<PatchedUserWatchHistory>;
export type WatchHistoryPartialUpdateMutationError = unknown;

/**
 * @summary Update User Watch History
 */
export const useWatchHistoryPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof watchHistoryPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedUserWatchHistory> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof watchHistoryPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedUserWatchHistory> },
  TContext
> => {
  const mutationOptions = getWatchHistoryPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
